---
title: "Data Science Project I"
author: "Sarah Salter"
date: "September 11, 2016"
output: html_document
---


## Traffic Fatalities Analysis Progress  (Date:9/30/16)
+ Identifying important variables for controling and identifying risk
+ Merging important variables within the 26 Datasets
+ Exploring Other Datasets that might be useful 
  -  1.  Police Databases for identifying all 'motor vehicles accidents' not just ones resulting in a fatality
  -  2.  Ad Campaigns Data
  -  3.  State Laws Data--  for traffic accident prevention (i.e- reprecussions for DUIs, violating provisional licenses
  -  4.  Street Light Data
   
+
+
+
+





## Traffic Fatalities Analysis Progress  (Date:9/23/16)

+ Downloaded all 26 Datasets 
  - Ex: Accident, Distract, Paperwork, Person, Vehicle, etc.   
+ Narrowed down Research Questions of Interest 
  - 1. What model could be developed to identify 'communities' that might be at risk fo fatal crashes?
  - 2. What are the characteristics of communities that in recent years have had the least risk?
  - 2. How does risk based on accident type differ geographically?  Is this risk consistent with previous years? 
+ Started Creating Codebook 
+ Determining Additional Variables to Create in Dataset
  - Was there increased driving in particular town/city, county, state, region? If so, why? How to code this?
  - Was there an increased amount of provisional licesnses issued in an given area?
  - Did the amount of traffic fatalities that have occured in the previous year surpass a certain amount?  

## Next Steps  (Date:9/23/16)
+ Need to more explicitly identify the 'community' I want to analyze
+ Find/scrape other datasets that could be useful
  - 1. Street Light Data, etc.
+ Merge All Datasets to Create a Final Dataset
